name: Uebercomputing
description: Continuous improvement through project, practices, self
meta_description: "Continuous improvement through project, practices, self"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: "http://uebercomputing.com"
google_analytics: "UA-45184534-1"
plugins: [jekyll-paginate]

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Details for the RSS feed generator
url: "http://uebercomputing.com"
author: "M. Dale"

# Disqus config
disqus-shortname: ""
